-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedantic_sha3]: external functions.
-- This is a template file: hax seeded PedanticSha3/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import PedanticSha3.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open pedantic_sha3

/-- [pedantic_sha3::bits::{impl core::clone::Clone for pedantic_sha3::bits::BitStr}::clone]:
    Source: 'sha3/spec/src/bits.rs', lines 66:4-71:5
    Visibility: public -/
axiom bits.BitStr.Insts.CoreCloneClone.clone
  : bits.BitStr → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::empty]:
    Source: 'sha3/spec/src/bits.rs', lines 77:4-82:5
    Visibility: public -/
axiom bits.BitStr.empty : RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::len]:
    Source: 'sha3/spec/src/bits.rs', lines 86:4-88:5
    Visibility: public -/
axiom bits.BitStr.len : bits.BitStr → RustM nat.Nat

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::is_empty]:
    Source: 'sha3/spec/src/bits.rs', lines 92:4-94:5
    Visibility: public -/
axiom bits.BitStr.is_empty : bits.BitStr → RustM Bool

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::bit]:
    Source: 'sha3/spec/src/bits.rs', lines 98:4-103:5
    Visibility: public -/
axiom bits.BitStr.bit : bits.BitStr → nat.Nat → RustM Bool

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::push_mut]:
    Source: 'sha3/spec/src/bits.rs', lines 109:4-118:5 -/
axiom bits.BitStr.push_mut : bits.BitStr → Bool → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::zeros]:
    Source: 'sha3/spec/src/bits.rs', lines 122:4-130:5
    Visibility: public -/
axiom bits.BitStr.zeros : nat.Nat → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::from_bits]:
    Source: 'sha3/spec/src/bits.rs', lines 137:4-143:5
    Visibility: public -/
axiom bits.BitStr.from_bits : Slice Bool → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::to_bits]:
    Source: 'sha3/spec/src/bits.rs', lines 151:4-161:5
    Visibility: public -/
axiom bits.BitStr.to_bits : bits.BitStr → RustM (alloc.vec.Vec Bool)

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::concat]:
    Source: 'sha3/spec/src/bits.rs', lines 165:4-171:5
    Visibility: public -/
axiom bits.BitStr.concat : bits.BitStr → bits.BitStr → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::trunc]:
    Source: 'sha3/spec/src/bits.rs', lines 175:4-183:5
    Visibility: public -/
axiom bits.BitStr.trunc : bits.BitStr → nat.Nat → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::slice]:
    Source: 'sha3/spec/src/bits.rs', lines 189:4-199:5
    Visibility: public -/
axiom bits.BitStr.slice
  : bits.BitStr → nat.Nat → nat.Nat → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::from_bytes]:
    Source: 'sha3/spec/src/bits.rs', lines 207:4-212:5
    Visibility: public -/
axiom bits.BitStr.from_bytes : Slice Std.U8 → RustM bits.BitStr

/-- [pedantic_sha3::bits::{pedantic_sha3::bits::BitStr}::to_bytes]:
    Source: 'sha3/spec/src/bits.rs', lines 219:4-221:5
    Visibility: public -/
axiom bits.BitStr.to_bytes : bits.BitStr → RustM (alloc.vec.Vec Std.U8)

/-- [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::le]:
    Source: 'sha3/spec/src/nat.rs', lines 191:4-193:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialOrdNat.le
  : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::ops::arith::Mul<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::mul]:
    Source: 'sha3/spec/src/nat.rs', lines 127:4-129:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreOpsArithMulNatNat.mul
  : nat.Nat → nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{pedantic_sha3::nat::Nat}::from_usize]:
    Source: 'sha3/spec/src/nat.rs', lines 76:4-78:5
    Visibility: public -/
axiom nat.Nat.from_usize : Std.Usize → RustM nat.Nat

/-- [pedantic_sha3::nat::{pedantic_sha3::nat::Nat}::new]:
    Source: 'sha3/spec/src/nat.rs', lines 69:4-71:5
    Visibility: public -/
axiom nat.Nat.new : Std.U128 → RustM nat.Nat

/-- [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::gt]:
    Source: 'sha3/spec/src/nat.rs', lines 196:4-198:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialOrdNat.gt
  : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::ops::arith::Rem<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::rem]:
    Source: 'sha3/spec/src/nat.rs', lines 148:4-151:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreOpsArithRemNatNat.rem
  : nat.Nat → nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{impl core::ops::arith::Sub<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::sub]:
    Source: 'sha3/spec/src/nat.rs', lines 113:4-118:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreOpsArithSubNatNat.sub
  : nat.Nat → nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{impl core::ops::arith::Add<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::add]:
    Source: 'sha3/spec/src/nat.rs', lines 102:4-104:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreOpsArithAddNatNat.add
  : nat.Nat → nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::lt]:
    Source: 'sha3/spec/src/nat.rs', lines 186:4-188:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialOrdNat.lt
  : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::cmp::PartialEq<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::eq]:
    Source: 'sha3/spec/src/nat.rs', lines 161:4-163:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialEqNat.eq : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::ops::arith::Div<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::div]:
    Source: 'sha3/spec/src/nat.rs', lines 137:4-140:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreOpsArithDivNatNat.div
  : nat.Nat → nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{pedantic_sha3::nat::Nat}::to_usize]:
    Source: 'sha3/spec/src/nat.rs', lines 87:4-93:5
    Visibility: public -/
axiom nat.Nat.to_usize : nat.Nat → RustM Std.Usize

/-- [pedantic_sha3::nat::{impl core::clone::Clone for pedantic_sha3::nat::Nat}::clone]:
    Source: 'sha3/spec/src/nat.rs', lines 56:4-58:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCloneClone.clone : nat.Nat → RustM nat.Nat

/-- [pedantic_sha3::nat::{impl core::cmp::PartialEq<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::ne]:
    Source: 'sha3/spec/src/nat.rs', lines 166:4-168:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialEqNat.ne : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::ge]:
    Source: 'sha3/spec/src/nat.rs', lines 201:4-203:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialOrdNat.ge
  : nat.Nat → nat.Nat → RustM Bool

/-- [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}::partial_cmp]:
    Source: 'sha3/spec/src/nat.rs', lines 175:4-183:5
    Visibility: public -/
axiom nat.Nat.Insts.CoreCmpPartialOrdNat.partial_cmp
  : nat.Nat → nat.Nat → RustM (core.option.Option core.cmp.Ordering)

