-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedantic_sha3]: function definitions
import Aeneas
import CoreModels
import PedanticSha3.Extraction.Types
import PedanticSha3.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedantic_sha3

/-- Trait implementation: [pedantic_sha3::bits::{impl core::clone::Clone for pedantic_sha3::bits::BitStr}]
    Source: 'sha3/spec/src/bits.rs', lines 64:0-72:1 -/
@[reducible]
impl_def bits.BitStr.Insts.CoreCloneClone : core.clone.Clone bits.BitStr := {
  clone := bits.BitStr.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    bits.BitStr.Insts.CoreCloneClone
}

/-- [pedantic_sha3::bits::trunc]: loop body 0:
    Source: 'sha3/spec/src/bits.rs', lines 228:4-230:5
    Visibility: public -/
@[rust_loop_body]
def bits.trunc_loop.body
  (x : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [pedantic_sha3::bits::trunc]: loop 0:
    Source: 'sha3/spec/src/bits.rs', lines 228:4-230:5
    Visibility: public -/
@[rust_loop]
def bits.trunc_loop
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.trunc_loop.body x iter1 out1)
    (iter, out)

/-- [pedantic_sha3::bits::trunc]:
    Source: 'sha3/spec/src/bits.rs', lines 225:0-232:1
    Visibility: public -/
def bits.trunc
  (x : Slice Bool) (s : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len x
  massert (s <= i)
  let out ← alloc.vec.Vec.new Bool
  bits.trunc_loop { start := 0#usize, «end» := s } x out

/-- [pedantic_sha3::bits::zeros]: loop body 0:
    Source: 'sha3/spec/src/bits.rs', lines 237:4-239:5
    Visibility: public -/
@[rust_loop_body]
def bits.zeros_loop.body
  (iter : core.ops.range.Range Std.Usize) (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some _ =>
    let out1 ← alloc.vec.Vec.push out false
    ok (cont (iter1, out1))

/-- [pedantic_sha3::bits::zeros]: loop 0:
    Source: 'sha3/spec/src/bits.rs', lines 237:4-239:5
    Visibility: public -/
@[rust_loop]
def bits.zeros_loop
  (iter : core.ops.range.Range Std.Usize) (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.zeros_loop.body iter1 out1)
    (iter, out)

/-- [pedantic_sha3::bits::zeros]:
    Source: 'sha3/spec/src/bits.rs', lines 235:0-241:1
    Visibility: public -/
def bits.zeros (n : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let out ← alloc.vec.Vec.new Bool
  bits.zeros_loop { start := 0#usize, «end» := n } out

/-- [pedantic_sha3::bits::concat]: loop body 0:
    Source: 'sha3/spec/src/bits.rs', lines 246:4-248:5
    Visibility: public -/
@[rust_loop_body]
def bits.concat_loop0.body
  (x : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [pedantic_sha3::bits::concat]: loop 0:
    Source: 'sha3/spec/src/bits.rs', lines 246:4-248:5
    Visibility: public -/
@[rust_loop]
def bits.concat_loop0
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.concat_loop0.body x iter1 out1)
    (iter, out)

/-- [pedantic_sha3::bits::concat]: loop body 1:
    Source: 'sha3/spec/src/bits.rs', lines 249:4-251:5
    Visibility: public -/
@[rust_loop_body]
def bits.concat_loop1.body
  (y : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize y i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [pedantic_sha3::bits::concat]: loop 1:
    Source: 'sha3/spec/src/bits.rs', lines 249:4-251:5
    Visibility: public -/
@[rust_loop]
def bits.concat_loop1
  (iter : core.ops.range.Range Std.Usize) (y : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.concat_loop1.body y iter1 out1)
    (iter, out)

/-- [pedantic_sha3::bits::concat]:
    Source: 'sha3/spec/src/bits.rs', lines 244:0-253:1
    Visibility: public -/
def bits.concat
  (x : Slice Bool) (y : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let out ← alloc.vec.Vec.new Bool
  let i ← core.slice.Slice.len x
  let out1 ← bits.concat_loop0 { start := 0#usize, «end» := i } x out
  let i1 ← core.slice.Slice.len y
  bits.concat_loop1 { start := 0#usize, «end» := i1 } y out1

/-- [pedantic_sha3::bits::xor]: loop body 0:
    Source: 'sha3/spec/src/bits.rs', lines 263:4-265:5
    Visibility: public -/
@[rust_loop_body]
def bits.xor_loop.body
  (x : Slice Bool) (y : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let b1 ← Slice.index_usize y i
    let out1 ← alloc.vec.Vec.push out (b ^^ b1)
    ok (cont (iter1, out1))

/-- [pedantic_sha3::bits::xor]: loop 0:
    Source: 'sha3/spec/src/bits.rs', lines 263:4-265:5
    Visibility: public -/
@[rust_loop]
def bits.xor_loop
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool) (y : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.xor_loop.body x y iter1 out1)
    (iter, out)

/-- [pedantic_sha3::bits::xor]:
    Source: 'sha3/spec/src/bits.rs', lines 257:0-267:1
    Visibility: public -/
def bits.xor
  (x : Slice Bool) (y : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len x
  let i1 ← core.slice.Slice.len y
  massert (i = i1)
  let out ← alloc.vec.Vec.new Bool
  bits.xor_loop { start := 0#usize, «end» := i } x y out

/-- [pedantic_sha3::bits::h2b]:
    Source: 'sha3/spec/src/bits.rs', lines 273:0-279:1
    Visibility: public -/
def bits.h2b (h : Slice Std.U8) (n : nat.Nat) : RustM bits.BitStr := do
  let i ← core.slice.Slice.len h
  let n1 ← nat.Nat.from_usize i
  let n2 ← nat.Nat.new 8#u128
  let n3 ← nat.Nat.Insts.CoreOpsArithMulNatNat.mul n1 n2
  let b ← nat.Nat.Insts.CoreCmpPartialOrdNat.le n n3
  massert b
  let bs ← bits.BitStr.from_bytes h
  bits.BitStr.trunc bs n

/-- [pedantic_sha3::bits::h2b_full]:
    Source: 'sha3/spec/src/bits.rs', lines 282:0-284:1
    Visibility: public -/
def bits.h2b_full (h : Slice Std.U8) : RustM bits.BitStr := do
  bits.BitStr.from_bytes h

/-- [pedantic_sha3::bits::b2h]:
    Source: 'sha3/spec/src/bits.rs', lines 290:0-292:1
    Visibility: public -/
def bits.b2h (s : bits.BitStr) : RustM (alloc.vec.Vec Std.U8) := do
  bits.BitStr.to_bytes s

/-- [pedantic_sha3::sponge::pad10_star_1]:
    Source: 'sha3/spec/src/sponge.rs', lines 12:0-23:1
    Visibility: public -/
def sponge.pad10_star_1 (x : nat.Nat) (m : nat.Nat) : RustM bits.BitStr := do
  let n ← nat.Nat.new 0#u128
  let b ← nat.Nat.Insts.CoreCmpPartialOrdNat.gt x n
  massert b
  let n1 ← nat.Nat.Insts.CoreOpsArithRemNatNat.rem m x
  let n2 ← nat.Nat.new 2#u128
  let n3 ← nat.Nat.Insts.CoreOpsArithAddNatNat.add n1 n2
  let n4 ← nat.Nat.Insts.CoreOpsArithRemNatNat.rem n3 x
  let n5 ← nat.Nat.Insts.CoreOpsArithSubNatNat.sub x n4
  let j ← nat.Nat.Insts.CoreOpsArithRemNatNat.rem n5 x
  let s ← lift (Array.to_slice (Array.make 1#usize [ true ]))
  let one ← bits.BitStr.from_bits s
  let bs ← bits.BitStr.zeros j
  let bs1 ← bits.BitStr.concat one bs
  bits.BitStr.concat bs1 one

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::Fn<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}::call]:
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
def sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnPairNatNatBitStr.call
  (c : sponge.keccak_c.closure_1) (tupled_args : (nat.Nat × nat.Nat)) :
  RustM bits.BitStr
  := do
  let (x, m) := tupled_args
  sponge.pad10_star_1 x m

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnMut<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}::call_mut]:
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
def
  sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnMutPairNatNatBitStr.call_mut
  (state : sponge.keccak_c.closure_1) (args : (nat.Nat × nat.Nat)) :
  RustM (bits.BitStr × sponge.keccak_c.closure_1)
  := do
  let bs ←
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnPairNatNatBitStr.call
      state args
  ok (bs, state)

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnOnce<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}::call_once]:
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
def
  sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnOncePairNatNatBitStr.call_once
  (c : sponge.keccak_c.closure_1) (p : (nat.Nat × nat.Nat)) :
  RustM bits.BitStr
  := do
  let (bs, _) ←
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnMutPairNatNatBitStr.call_mut
      c p
  ok bs

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnOnce<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}]
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
@[reducible]
def sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnOncePairNatNatBitStr :
  core.ops.function.FnOnce sponge.keccak_c.closure_1 (nat.Nat × nat.Nat)
  bits.BitStr := {
  call_once :=
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnOncePairNatNatBitStr.call_once
}

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnMut<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}]
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
@[reducible]
def sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnMutPairNatNatBitStr :
  core.ops.function.FnMut sponge.keccak_c.closure_1 (nat.Nat × nat.Nat)
  bits.BitStr := {
  FnOnceInst :=
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnOncePairNatNatBitStr
  call_mut :=
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnMutPairNatNatBitStr.call_mut
}

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::Fn<(pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat), pedantic_sha3::bits::BitStr> for pedantic_sha3::sponge::keccak_c::closure#1}]
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
@[reducible]
def sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnPairNatNatBitStr :
  core.ops.function.Fn sponge.keccak_c.closure_1 (nat.Nat × nat.Nat)
  bits.BitStr := {
  FnMutInst :=
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnMutPairNatNatBitStr
  call :=
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnPairNatNatBitStr.call
}

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::B]
    Source: 'sha3/spec/src/state_array.rs', lines 27:4-27:32
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.B (W : Std.Usize) : RustM Std.Usize := 25#usize * W

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop body 2:
    Source: 'sha3/spec/src/state_array.rs', lines 77:16-79:17
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0_loop0_loop0.body
  {W : Std.Usize} (self : state_array.StateArray W) (y : Std.Usize)
  (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    ((state_array.StateArray W) × (alloc.vec.Vec Bool)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (self, s))
  | core.option.Option.Some z =>
    let a ← Array.index_usize self.a x
    let _ ← Array.index_usize a y
    let a1 ← Array.index_usize a y
    let b ← Array.index_usize a1 z
    let s1 ← alloc.vec.Vec.push s b
    ok (cont (iter1, s1))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop 2:
    Source: 'sha3/spec/src/state_array.rs', lines 77:16-79:17
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) (y : Std.Usize)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (iter1, s1) => state_array.StateArray.to_bits_loop0_loop0_loop0.body
      self y x iter1 s1)
    (iter, s)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop body 1:
    Source: 'sha3/spec/src/state_array.rs', lines 76:12-80:13
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0_loop0.body
  {W : Std.Usize} (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (alloc.vec.Vec Bool))
    ((state_array.StateArray W) × (alloc.vec.Vec Bool)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (self, s))
  | core.option.Option.Some x =>
    let (self1, s1) ←
      state_array.StateArray.to_bits_loop0_loop0_loop0
        { start := 0#usize, «end» := W } self s y x
    ok (cont (iter1, self1, s1))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop 1:
    Source: 'sha3/spec/src/state_array.rs', lines 76:12-80:13
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (iter1, self1, s1) => state_array.StateArray.to_bits_loop0_loop0.body
      y iter1 self1 s1)
    (iter, self, s)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop body 0:
    Source: 'sha3/spec/src/state_array.rs', lines 75:8-81:9
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (alloc.vec.Vec Bool)) (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done s)
  | core.option.Option.Some y =>
    let (self1, s1) ←
      state_array.StateArray.to_bits_loop0_loop0
        { start := 0#usize, «end» := 5#usize } self s y
    ok (cont (iter1, self1, s1))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]: loop 0:
    Source: 'sha3/spec/src/state_array.rs', lines 75:8-81:9
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, self1, s1) => state_array.StateArray.to_bits_loop0.body iter1
      self1 s1)
    (iter, self, s)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::to_bits]:
    Source: 'sha3/spec/src/state_array.rs', lines 73:4-83:5
    Visibility: public -/
def state_array.StateArray.to_bits
  {W : Std.Usize} (self : state_array.StateArray W) :
  RustM (alloc.vec.Vec Bool)
  := do
  let i ← state_array.StateArray.B W
  let s ← alloc.vec.Vec.with_capacity Bool i
  state_array.StateArray.to_bits_loop0 { start := 0#usize, «end» := 5#usize }
    self s

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::zero]:
    Source: 'sha3/spec/src/state_array.rs', lines 47:4-51:5
    Visibility: public -/
def state_array.StateArray.zero
  (W : Std.Usize) : RustM (state_array.StateArray W) := do
  let a := Array.repeat W false
  let a1 := Array.repeat 5#usize a
  let a2 := Array.repeat 5#usize a1
  ok { a := a2 }

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop body 2:
    Source: 'sha3/spec/src/state_array.rs', lines 60:16-62:17
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0_loop0_loop0.body
  {W : Std.Usize} (s : Slice Bool) (x : Std.Usize) (y : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some z =>
    let i ← 5#usize * y
    let i1 ← i + x
    let i2 ← W * i1
    let i3 ← i2 + z
    let b ← Slice.index_usize s i3
    let a ← Array.index_usize out.a x
    let _ ← Array.index_usize a y
    let (a1, index_mut_back) ← Array.index_mut_usize out.a x
    let (a2, index_mut_back1) ← Array.index_mut_usize a1 y
    let a3 ← Array.update a2 z b
    let a4 := index_mut_back1 a3
    let a5 := index_mut_back a4
    ok (cont (iter1, { a := a5 }))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop 2:
    Source: 'sha3/spec/src/state_array.rs', lines 60:16-62:17
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) (x : Std.Usize) (y : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) =>
      state_array.StateArray.from_bits_loop0_loop0_loop0.body s x y iter1 out1)
    (iter, out)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop body 1:
    Source: 'sha3/spec/src/state_array.rs', lines 59:12-63:13
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0_loop0.body
  {W : Std.Usize} (s : Slice Bool) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some y =>
    let out1 ←
      state_array.StateArray.from_bits_loop0_loop0_loop0
        { start := 0#usize, «end» := W } s out x y
    ok (cont (iter1, out1))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop 1:
    Source: 'sha3/spec/src/state_array.rs', lines 59:12-63:13
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) (x : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) => state_array.StateArray.from_bits_loop0_loop0.body s x
      iter1 out1)
    (iter, out)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop body 0:
    Source: 'sha3/spec/src/state_array.rs', lines 58:8-64:9
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0.body
  {W : Std.Usize} (s : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let out1 ←
      state_array.StateArray.from_bits_loop0_loop0
        { start := 0#usize, «end» := 5#usize } s out x
    ok (cont (iter1, out1))

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]: loop 0:
    Source: 'sha3/spec/src/state_array.rs', lines 58:8-64:9
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) => state_array.StateArray.from_bits_loop0.body s iter1
      out1)
    (iter, out)

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::from_bits]:
    Source: 'sha3/spec/src/state_array.rs', lines 55:4-66:5
    Visibility: public -/
def state_array.StateArray.from_bits
  (W : Std.Usize) (s : Slice Bool) : RustM (state_array.StateArray W) := do
  let i ← core.slice.Slice.len s
  let i1 ← 25#usize * W
  massert (i = i1)
  let out ← state_array.StateArray.zero W
  state_array.StateArray.from_bits_loop0
    { start := 0#usize, «end» := 5#usize } s out

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::L]
    Source: 'sha3/spec/src/state_array.rs', lines 35:4-44:6
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.L (W : Std.Usize) : RustM Std.Usize :=
  match W.val with
  | 1 => ok 0#usize
  | 2 => ok 1#usize
  | 4 => ok 2#usize
  | 8 => ok 3#usize
  | 16 => ok 4#usize
  | 32 => ok 5#usize
  | 64 => ok 6#usize
  | _ => fail panic

/-- [pedantic_sha3::step_mappings::imod]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 14:0-16:1 -/
def step_mappings.imod (a : Std.I64) (b : Std.I64) : RustM Std.Usize := do
  let i ← a % b
  let i1 ← i + b
  let i2 ← i1 % b
  ok (IScalar.hcast .Usize i2)

/-- [pedantic_sha3::step_mappings::rc]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 122:4-137:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rc_loop.body
  (iter : core.ops.range.RangeInclusive Std.Usize) (r : Array Bool 9#usize) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.Usize) × (Array Bool
    9#usize)) (Array Bool 9#usize))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done r)
  | core.option.Option.Some _ =>
    let shifted := Array.repeat 9#usize false
    let (s, index_mut_back) ←
      core.Array.Insts.CoreOpsIndexIndexMut.index_mut
        (core.Slice.Insts.CoreOpsIndexIndexMut
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Bool)) shifted { start := 1#usize, «end» := 9#usize }
    let s1 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Bool)) r { start := 0#usize, «end» := 8#usize }
    let s2 ←
      core.slice.Slice.copy_from_slice core.Bool.Insts.CoreMarkerCopy s s1
    let shifted1 := index_mut_back s2
    let b ← Array.index_usize shifted1 8#usize
    let b1 ← Array.index_usize shifted1 0#usize
    let shifted2 ← Array.update shifted1 0#usize (b1 ^^ b)
    let b2 ← Array.index_usize shifted2 8#usize
    let b3 ← Array.index_usize shifted2 4#usize
    let shifted3 ← Array.update shifted2 4#usize (b3 ^^ b2)
    let b4 ← Array.index_usize shifted3 8#usize
    let b5 ← Array.index_usize shifted3 5#usize
    let shifted4 ← Array.update shifted3 5#usize (b5 ^^ b4)
    let b6 ← Array.index_usize shifted4 8#usize
    let b7 ← Array.index_usize shifted4 6#usize
    let shifted5 ← Array.update shifted4 6#usize (b7 ^^ b6)
    let a ← Array.update shifted5 8#usize false
    ok (cont (iter1, a))

/-- [pedantic_sha3::step_mappings::rc]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 122:4-137:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rc_loop
  (iter : core.ops.range.RangeInclusive Std.Usize) (r : Array Bool 9#usize) :
  RustM (Array Bool 9#usize)
  := do
  loop
    (fun (iter1, r1) => step_mappings.rc_loop.body iter1 r1)
    (iter, r)

/-- [pedantic_sha3::step_mappings::rc]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 112:0-140:1
    Visibility: public -/
def step_mappings.rc (t : Std.I64) : RustM Bool := do
  let t1 ← step_mappings.imod t 255#i64
  if t1 = 0#usize
  then ok true
  else
    let r := Array.repeat 9#usize false
    let a ← Array.update r 0#usize true
    let iter ← core.ops.range.RangeInclusive.new 1#usize t1
    let r1 ← step_mappings.rc_loop iter a
    Array.index_usize r1 0#usize

/-- [pedantic_sha3::step_mappings::iota]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 151:4-153:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.iota_loop0.body
  {W : Std.Usize} (i_r : Std.I64)
  (iter : core.ops.range.RangeInclusive Std.Usize)
  (round_constant : Array Bool W) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.Usize) × (Array Bool
    W)) (Array Bool W))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done round_constant)
  | core.option.Option.Some j =>
    let i ← lift (UScalar.hcast .I64 j)
    let i1 ← 7#i64 * i_r
    let i2 ← i + i1
    let b ← step_mappings.rc i2
    let i3 ← 1#usize <<< j
    let i4 ← i3 - 1#usize
    let a ← Array.update round_constant i4 b
    ok (cont (iter1, a))

/-- [pedantic_sha3::step_mappings::iota]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 151:4-153:5
    Visibility: public -/
@[rust_loop]
def step_mappings.iota_loop0
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.Usize)
  (i_r : Std.I64) (round_constant : Array Bool W) :
  RustM (Array Bool W)
  := do
  loop
    (fun (iter1, round_constant1) => step_mappings.iota_loop0.body i_r iter1
      round_constant1)
    (iter, round_constant)

/-- [pedantic_sha3::step_mappings::iota]: loop body 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 160:4-162:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.iota_loop1.body
  {W : Std.Usize} (round_constant : Array Bool W)
  (iter : core.ops.range.Range Std.Usize) (lane : Array Bool W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Bool W))
    (Array Bool W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done lane)
  | core.option.Option.Some z =>
    let b ← Array.index_usize round_constant z
    let b1 ← Array.index_usize lane z
    let a ← Array.update lane z (b1 ^^ b)
    ok (cont (iter1, a))

/-- [pedantic_sha3::step_mappings::iota]: loop 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 160:4-162:5
    Visibility: public -/
@[rust_loop]
def step_mappings.iota_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (round_constant : Array Bool W) (lane : Array Bool W) :
  RustM (Array Bool W)
  := do
  loop
    (fun (iter1, lane1) => step_mappings.iota_loop1.body round_constant iter1
      lane1)
    (iter, lane)

/-- [pedantic_sha3::step_mappings::iota]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 143:0-165:1
    Visibility: public -/
def step_mappings.iota
  {W : Std.Usize} (a : state_array.StateArray W) (i_r : Std.I64) :
  RustM (state_array.StateArray W)
  := do
  let round_constant := Array.repeat W false
  let i ← state_array.StateArray.L W
  let iter ← core.ops.range.RangeInclusive.new 0#usize i
  let round_constant1 ← step_mappings.iota_loop0 iter i_r round_constant
  let a1 ← Array.index_usize a.a 0#usize
  let lane ← Array.index_usize a1 0#usize
  let lane1 ←
    step_mappings.iota_loop1 { start := 0#usize, «end» := W } round_constant1
      lane
  let (a2, index_mut_back) ← Array.index_mut_usize a.a 0#usize
  let a3 ← Array.update a2 0#usize lane1
  let a4 := index_mut_back a3
  ok { a := a4 }

/-- [pedantic_sha3::step_mappings::chi]: loop body 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 98:12-100:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 z
    let i ← x + 1#usize
    let i1 ← i % 5#usize
    let a3 ← Array.index_usize a.a i1
    let _ ← Array.index_usize a3 y
    let a4 ← Array.index_usize a3 y
    let b1 ← Array.index_usize a4 z
    let i2 ← x + 2#usize
    let i3 ← i2 % 5#usize
    let a5 ← Array.index_usize a.a i3
    let _ ← Array.index_usize a5 y
    let a6 ← Array.index_usize a5 y
    let b2 ← Array.index_usize a6 z
    let a7 ← Array.index_usize out.a x
    let _ ← Array.index_usize a7 y
    let (a8, index_mut_back) ← Array.index_mut_usize out.a x
    let (a9, index_mut_back1) ← Array.index_mut_usize a8 y
    let a10 ← Array.update a9 z (b ^^ ((¬ b1) && b2))
    let a11 := index_mut_back1 a10
    let a12 := index_mut_back a11
    ok (cont (iter1, { a := a12 }))

/-- [pedantic_sha3::step_mappings::chi]: loop 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 98:12-100:13
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.chi_loop0_loop0_loop0.body a x y iter1
      out1)
    (iter, out)

/-- [pedantic_sha3::step_mappings::chi]: loop body 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 97:8-101:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0_loop0.body
  {W : Std.Usize} (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.chi_loop0_loop0_loop0 { start := 0#usize, «end» := W } a
        out x y
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::chi]: loop 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 97:8-101:9
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.chi_loop0_loop0.body x iter1 a1
      out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::chi]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 96:4-102:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.chi_loop0_loop0 { start := 0#usize, «end» := 5#usize } a
        out x
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::chi]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 96:4-102:5
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.chi_loop0.body iter1 a1 out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::chi]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 93:0-104:1
    Visibility: public -/
def step_mappings.chi
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let out ← state_array.StateArray.zero W
  step_mappings.chi_loop0 { start := 0#usize, «end» := 5#usize } a out

/-- [pedantic_sha3::step_mappings::pi]: loop body 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 84:12-86:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let i ← 3#usize * y
    let i1 ← x + i
    let i2 ← i1 % 5#usize
    let a1 ← Array.index_usize a.a i2
    let _ ← Array.index_usize a1 x
    let a2 ← Array.index_usize a1 x
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize out.a x
    let _ ← Array.index_usize a3 y
    let (a4, index_mut_back) ← Array.index_mut_usize out.a x
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 y
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [pedantic_sha3::step_mappings::pi]: loop 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 84:12-86:13
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.pi_loop0_loop0_loop0.body a x y iter1
      out1)
    (iter, out)

/-- [pedantic_sha3::step_mappings::pi]: loop body 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 83:8-87:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0_loop0.body
  {W : Std.Usize} (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.pi_loop0_loop0_loop0 { start := 0#usize, «end» := W } a
        out x y
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::pi]: loop 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 83:8-87:9
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.pi_loop0_loop0.body x iter1 a1
      out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::pi]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 82:4-88:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.pi_loop0_loop0 { start := 0#usize, «end» := 5#usize } a
        out x
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::pi]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 82:4-88:5
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.pi_loop0.body iter1 a1 out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::pi]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 79:0-90:1
    Visibility: public -/
def step_mappings.pi
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let out ← state_array.StateArray.zero W
  step_mappings.pi_loop0 { start := 0#usize, «end» := 5#usize } a out

/-- [pedantic_sha3::step_mappings::rho]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 56:4-58:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a 0#usize
    let _ ← Array.index_usize a1 0#usize
    let a2 ← Array.index_usize a1 0#usize
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize out.a 0#usize
    let _ ← Array.index_usize a3 0#usize
    let (a4, index_mut_back) ← Array.index_mut_usize out.a 0#usize
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 0#usize
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [pedantic_sha3::step_mappings::rho]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 56:4-58:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.rho_loop0.body a iter1 out1)
    (iter, out)

/-- [pedantic_sha3::step_mappings::rho]: loop body 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 67:8-69:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop1_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (w : Std.I64) (x : Std.Usize)
  (y : Std.Usize) (offset : Std.I64) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    massert (y < 5#usize)
    let i ← lift (UScalar.hcast .I64 z)
    let i1 ← i - offset
    let i2 ← step_mappings.imod i1 w
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 i2
    let a3 ← Array.index_usize out.a x
    let _ ← Array.index_usize a3 y
    let (a4, index_mut_back) ← Array.index_mut_usize out.a x
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 y
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [pedantic_sha3::step_mappings::rho]: loop 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 67:8-69:9
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop1_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (w : Std.I64) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) (offset : Std.I64) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.rho_loop1_loop0.body a w x y offset
      iter1 out1)
    (iter, out)

/-- [pedantic_sha3::step_mappings::rho]: loop body 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 64:4-74:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop1.body
  {W : Std.Usize} (w : Std.I64) (iter : core.ops.range.Range Std.I64)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.I64) × (state_array.StateArray
    W) × (state_array.StateArray W) × Std.Usize × Std.Usize)
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.I64.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some t =>
    let i ← t + 1#i64
    let i1 ← t + 2#i64
    let i2 ← i * i1
    let offset ← i2 / 2#i64
    let (a1, out1) ←
      step_mappings.rho_loop1_loop0 { start := 0#usize, «end» := W } a w out
        x y offset
    let i3 ← 2#usize * x
    let i4 ← 3#usize * y
    let i5 ← i3 + i4
    let ny ← i5 % 5#usize
    ok (cont (iter1, a1, out1, y, ny))

/-- [pedantic_sha3::step_mappings::rho]: loop 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 64:4-74:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.I64)
  (a : state_array.StateArray W) (w : Std.I64) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1, x1, y1) => step_mappings.rho_loop1.body w iter1 a1
      out1 x1 y1)
    (iter, a, out, x, y)

/-- [pedantic_sha3::step_mappings::rho]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 51:0-76:1
    Visibility: public -/
def step_mappings.rho
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let w ← lift (UScalar.hcast .I64 W)
  let out ← state_array.StateArray.zero W
  let (a1, out1) ←
    step_mappings.rho_loop0 { start := 0#usize, «end» := W } a out
  step_mappings.rho_loop1 { start := 0#i64, «end» := 24#i64 } a1 w out1
    1#usize 0#usize

/-- [pedantic_sha3::step_mappings::theta]: loop body 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 25:8-27:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (c : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) ((state_array.StateArray W) × (Array (Array Bool W) 5#usize)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, c))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 0#usize
    let a2 ← Array.index_usize a1 0#usize
    let b ← Array.index_usize a2 z
    let _ ← Array.index_usize a1 1#usize
    let a3 ← Array.index_usize a1 1#usize
    let b1 ← Array.index_usize a3 z
    let _ ← Array.index_usize a1 2#usize
    let a4 ← Array.index_usize a1 2#usize
    let b2 ← Array.index_usize a4 z
    let _ ← Array.index_usize a1 3#usize
    let a5 ← Array.index_usize a1 3#usize
    let b3 ← Array.index_usize a5 z
    let _ ← Array.index_usize a1 4#usize
    let a6 ← Array.index_usize a1 4#usize
    let b4 ← Array.index_usize a6 z
    let (a7, index_mut_back) ← Array.index_mut_usize c x
    let a8 ← Array.update a7 z ((((b ^^ b1) ^^ b2) ^^ b3) ^^ b4)
    let a9 := index_mut_back a8
    ok (cont (iter1, a9))

/-- [pedantic_sha3::step_mappings::theta]: loop 1:
    Source: 'sha3/spec/src/step_mappings.rs', lines 25:8-27:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (Array (Array Bool W) 5#usize))
  := do
  loop
    (fun (iter1, c1) => step_mappings.theta_loop0_loop0.body a x iter1 c1)
    (iter, c)

/-- [pedantic_sha3::step_mappings::theta]: loop body 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 24:4-28:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (Array (Array Bool W) 5#usize))
    ((state_array.StateArray W) × (Array (Array Bool W) 5#usize)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, c))
  | core.option.Option.Some x =>
    let (a1, c1) ←
      step_mappings.theta_loop0_loop0 { start := 0#usize, «end» := W } a c x
    ok (cont (iter1, a1, c1))

/-- [pedantic_sha3::step_mappings::theta]: loop 0:
    Source: 'sha3/spec/src/step_mappings.rs', lines 24:4-28:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize) :
  RustM ((state_array.StateArray W) × (Array (Array Bool W) 5#usize))
  := do
  loop
    (fun (iter1, a1, c1) => step_mappings.theta_loop0.body iter1 a1 c1)
    (iter, a, c)

/-- [pedantic_sha3::step_mappings::theta]: loop body 3:
    Source: 'sha3/spec/src/step_mappings.rs', lines 33:8-35:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop1_loop0.body
  {W : Std.Usize} (w : Std.I64) (c : Array (Array Bool W) 5#usize)
  (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (d : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) (Array (Array Bool W) 5#usize))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done d)
  | core.option.Option.Some z =>
    let i ← lift (UScalar.hcast .I64 x)
    let i1 ← i - 1#i64
    let i2 ← step_mappings.imod i1 5#i64
    let a ← Array.index_usize c i2
    let b ← Array.index_usize a z
    let i3 ← x + 1#usize
    let i4 ← i3 % 5#usize
    massert (i4 < 5#usize)
    let i5 ← lift (UScalar.hcast .I64 z)
    let i6 ← i5 - 1#i64
    let i7 ← step_mappings.imod i6 w
    let a1 ← Array.index_usize c i4
    let b1 ← Array.index_usize a1 i7
    let (a2, index_mut_back) ← Array.index_mut_usize d x
    let a3 ← Array.update a2 z (b ^^ b1)
    let a4 := index_mut_back a3
    ok (cont (iter1, a4))

/-- [pedantic_sha3::step_mappings::theta]: loop 3:
    Source: 'sha3/spec/src/step_mappings.rs', lines 33:8-35:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop1_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (w : Std.I64)
  (c : Array (Array Bool W) 5#usize) (d : Array (Array Bool W) 5#usize)
  (x : Std.Usize) :
  RustM (Array (Array Bool W) 5#usize)
  := do
  loop
    (fun (iter1, d1) => step_mappings.theta_loop1_loop0.body w c x iter1 d1)
    (iter, d)

/-- [pedantic_sha3::step_mappings::theta]: loop body 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 32:4-36:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop1.body
  {W : Std.Usize} (w : Std.I64) (c : Array (Array Bool W) 5#usize)
  (iter : core.ops.range.Range Std.Usize) (d : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) (Array (Array Bool W) 5#usize))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done d)
  | core.option.Option.Some x =>
    let d1 ←
      step_mappings.theta_loop1_loop0 { start := 0#usize, «end» := W } w c d
        x
    ok (cont (iter1, d1))

/-- [pedantic_sha3::step_mappings::theta]: loop 2:
    Source: 'sha3/spec/src/step_mappings.rs', lines 32:4-36:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (w : Std.I64)
  (c : Array (Array Bool W) 5#usize) (d : Array (Array Bool W) 5#usize) :
  RustM (Array (Array Bool W) 5#usize)
  := do
  loop
    (fun (iter1, d1) => step_mappings.theta_loop1.body w c iter1 d1)
    (iter, d)

/-- [pedantic_sha3::step_mappings::theta]: loop body 6:
    Source: 'sha3/spec/src/step_mappings.rs', lines 42:12-44:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W)
  (d : Array (Array Bool W) 5#usize) (x : Std.Usize) (y : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize d x
    let b1 ← Array.index_usize a3 z
    let a4 ← Array.index_usize out.a x
    let _ ← Array.index_usize a4 y
    let (a5, index_mut_back) ← Array.index_mut_usize out.a x
    let (a6, index_mut_back1) ← Array.index_mut_usize a5 y
    let a7 ← Array.update a6 z (b ^^ b1)
    let a8 := index_mut_back1 a7
    let a9 := index_mut_back a8
    ok (cont (iter1, { a := a9 }))

/-- [pedantic_sha3::step_mappings::theta]: loop 6:
    Source: 'sha3/spec/src/step_mappings.rs', lines 42:12-44:13
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.theta_loop2_loop0_loop0.body a d x y
      iter1 out1)
    (iter, out)

/-- [pedantic_sha3::step_mappings::theta]: loop body 5:
    Source: 'sha3/spec/src/step_mappings.rs', lines 41:8-45:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2_loop0.body
  {W : Std.Usize} (d : Array (Array Bool W) 5#usize) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (a : state_array.StateArray W)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.theta_loop2_loop0_loop0 { start := 0#usize, «end» := W }
        a d out x y
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::theta]: loop 5:
    Source: 'sha3/spec/src/step_mappings.rs', lines 41:8-45:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.theta_loop2_loop0.body d x iter1 a1
      out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::theta]: loop body 4:
    Source: 'sha3/spec/src/step_mappings.rs', lines 40:4-46:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2.body
  {W : Std.Usize} (d : Array (Array Bool W) 5#usize)
  (iter : core.ops.range.Range Std.Usize) (a : state_array.StateArray W)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.theta_loop2_loop0 { start := 0#usize, «end» := 5#usize }
        a d out x
    ok (cont (iter1, a1, out1))

/-- [pedantic_sha3::step_mappings::theta]: loop 4:
    Source: 'sha3/spec/src/step_mappings.rs', lines 40:4-46:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.theta_loop2.body d iter1 a1 out1)
    (iter, a, out)

/-- [pedantic_sha3::step_mappings::theta]:
    Source: 'sha3/spec/src/step_mappings.rs', lines 19:0-48:1
    Visibility: public -/
def step_mappings.theta
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let w ← lift (UScalar.hcast .I64 W)
  let a1 := Array.repeat W false
  let c := Array.repeat 5#usize a1
  let (a2, c1) ←
    step_mappings.theta_loop0 { start := 0#usize, «end» := 5#usize } a c
  let a3 := Array.repeat W false
  let d := Array.repeat 5#usize a3
  let d1 ←
    step_mappings.theta_loop1 { start := 0#usize, «end» := 5#usize } w c1 d
  step_mappings.theta_loop2 { start := 0#usize, «end» := 5#usize } a2 d1 a2

/-- [pedantic_sha3::keccak_p::rnd]:
    Source: 'sha3/spec/src/keccak_p.rs', lines 8:0-10:1
    Visibility: public -/
def keccak_p.rnd
  {W : Std.Usize} (a : state_array.StateArray W) (i_r : Std.I64) :
  RustM (state_array.StateArray W)
  := do
  let sa ← step_mappings.theta a
  let sa1 ← step_mappings.rho sa
  let sa2 ← step_mappings.pi sa1
  let sa3 ← step_mappings.chi sa2
  step_mappings.iota sa3 i_r

/-- [pedantic_sha3::keccak_p::keccak_p]: loop body 0:
    Source: 'sha3/spec/src/keccak_p.rs', lines 35:4-37:5
    Visibility: public -/
@[rust_loop_body]
def keccak_p.keccak_p_loop.body
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.I64)
  (a : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.I64) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.I64.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done a)
  | core.option.Option.Some i_r =>
    let a1 ← keccak_p.rnd a i_r
    ok (cont (iter1, a1))

/-- [pedantic_sha3::keccak_p::keccak_p]: loop 0:
    Source: 'sha3/spec/src/keccak_p.rs', lines 35:4-37:5
    Visibility: public -/
@[rust_loop]
def keccak_p.keccak_p_loop
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.I64)
  (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1) => keccak_p.keccak_p_loop.body iter1 a1)
    (iter, a)

/-- [pedantic_sha3::keccak_p::keccak_p]:
    Source: 'sha3/spec/src/keccak_p.rs', lines 15:0-42:1
    Visibility: public -/
def keccak_p.keccak_p
  (W : Std.Usize) (s : Slice Bool) (n_r : Std.Usize) :
  RustM (alloc.vec.Vec Bool)
  := do
  massert (n_r > 0#usize)
  let i ← lift (UScalar.cast .Usize core.num.U32.MAX)
  massert (n_r <= i)
  let a ← state_array.StateArray.from_bits W s
  let i1 ← state_array.StateArray.L W
  let i2 ← lift (UScalar.hcast .I64 i1)
  let i3 ← 2#i64 * i2
  let i4 ← 12#i64 + i3
  let last ← i4 - 1#i64
  let i5 ← lift (UScalar.hcast .I64 n_r)
  let i6 ← last - i5
  let first ← i6 + 1#i64
  let iter ← core.ops.range.RangeInclusive.new first last
  let a1 ← keccak_p.keccak_p_loop iter a
  state_array.StateArray.to_bits a1

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::Fn<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}::call]:
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
def
  sponge.keccak_c.closure.Insts.CoreOpsFunctionFnTupleSharedSliceBoolVecBool.call
  (c : sponge.keccak_c.closure) (tupled_args : Slice Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  keccak_p.keccak_p 64#usize tupled_args 24#usize

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnMut<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}::call_mut]:
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
def
  sponge.keccak_c.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceBoolVecBool.call_mut
  (state : sponge.keccak_c.closure) (args : Slice Bool) :
  RustM ((alloc.vec.Vec Bool) × sponge.keccak_c.closure)
  := do
  let v ←
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnTupleSharedSliceBoolVecBool.call
      state args
  ok (v, state)

/-- [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnOnce<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}::call_once]:
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
def
  sponge.keccak_c.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceBoolVecBool.call_once
  (c : sponge.keccak_c.closure) (s : Slice Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  let (v, _) ←
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceBoolVecBool.call_mut
      c s
  ok v

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnOnce<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}]
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
@[reducible]
def
  sponge.keccak_c.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceBoolVecBool
  : core.ops.function.FnOnce sponge.keccak_c.closure (Slice Bool)
  (alloc.vec.Vec Bool) := {
  call_once :=
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceBoolVecBool.call_once
}

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::FnMut<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}]
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
@[reducible]
def
  sponge.keccak_c.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceBoolVecBool
  : core.ops.function.FnMut sponge.keccak_c.closure (Slice Bool) (alloc.vec.Vec
  Bool) := {
  FnOnceInst :=
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceBoolVecBool
  call_mut :=
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceBoolVecBool.call_mut
}

/-- Trait implementation: [pedantic_sha3::sponge::keccak_c::{impl core::ops::function::Fn<(&'_ [bool],), alloc::vec::Vec<bool>> for pedantic_sha3::sponge::keccak_c::closure}]
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
@[reducible]
def sponge.keccak_c.closure.Insts.CoreOpsFunctionFnTupleSharedSliceBoolVecBool
  : core.ops.function.Fn sponge.keccak_c.closure (Slice Bool) (alloc.vec.Vec
  Bool) := {
  FnMutInst :=
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceBoolVecBool
  call :=
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnTupleSharedSliceBoolVecBool.call
}

/-- [pedantic_sha3::sponge::B]
    Source: 'sha3/spec/src/sponge.rs', lines 91:0-91:26
    Visibility: public -/
@[global_simps, irreducible] def sponge.B : Std.Usize := 1600#usize

/-- [pedantic_sha3::sponge::sponge]: loop body 0:
    Source: 'sha3/spec/src/sponge.rs', lines 66:4-70:5
    Visibility: public -/
@[rust_loop_body]
def sponge.sponge_loop0.body
  {T0 : Type} (coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst :
  core.ops.function.Fn T0 (Slice Bool) (alloc.vec.Vec Bool)) (f : T0)
  (r : nat.Nat) (p : bits.BitStr) (blocks : nat.Nat) (c : Std.Usize)
  (s : alloc.vec.Vec Bool) (i : nat.Nat) :
  RustM (ControlFlow ((alloc.vec.Vec Bool) × nat.Nat) (alloc.vec.Vec Bool))
  := do
  let b ← nat.Nat.Insts.CoreCmpPartialOrdNat.lt i blocks
  if b
  then
    let n ← nat.Nat.Insts.CoreOpsArithMulNatNat.mul i r
    let bs ← bits.BitStr.slice p n r
    let v ← bits.BitStr.to_bits bs
    let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
    let v1 ← bits.zeros c
    let s2 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
    let block ← bits.concat s1 s2
    let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref s
    let s4 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref block
    let v2 ← bits.xor s3 s4
    let s5 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v2
    let s6 ← coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst.call f s5
    let n1 ← nat.Nat.new 1#u128
    let i1 ← nat.Nat.Insts.CoreOpsArithAddNatNat.add i n1
    ok (cont (s6, i1))
  else ok (done s)

/-- [pedantic_sha3::sponge::sponge]: loop 0:
    Source: 'sha3/spec/src/sponge.rs', lines 66:4-70:5
    Visibility: public -/
@[rust_loop]
def sponge.sponge_loop0
  {T0 : Type} (coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst :
  core.ops.function.Fn T0 (Slice Bool) (alloc.vec.Vec Bool)) (f : T0)
  (r : nat.Nat) (p : bits.BitStr) (blocks : nat.Nat) (c : Std.Usize)
  (s : alloc.vec.Vec Bool) (i : nat.Nat) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (s1, i1) => sponge.sponge_loop0.body
      coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst f r p blocks c s1 i1)
    (s, i)

/-- [pedantic_sha3::sponge::sponge]: loop body 1:
    Source: 'sha3/spec/src/sponge.rs', lines 73:4-83:5
    Visibility: public -/
@[rust_loop_body]
def sponge.sponge_loop1.body
  {T0 : Type} (coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst :
  core.ops.function.Fn T0 (Slice Bool) (alloc.vec.Vec Bool)) (f : T0)
  (r : nat.Nat) (d : nat.Nat) (s : alloc.vec.Vec Bool) (z : bits.BitStr) :
  RustM (ControlFlow ((alloc.vec.Vec Bool) × bits.BitStr) bits.BitStr)
  := do
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref s
  let i ← nat.Nat.to_usize r
  let head ← bits.trunc s1 i
  let s2 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref head
  let bs ← bits.BitStr.from_bits s2
  let z1 ← bits.BitStr.concat z bs
  let n ← bits.BitStr.len z1
  let b ← nat.Nat.Insts.CoreCmpPartialOrdNat.le d n
  if b
  then ok (done z1)
  else
    let s3 ← coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst.call f s1
    ok (cont (s3, z1))

/-- [pedantic_sha3::sponge::sponge]: loop 1:
    Source: 'sha3/spec/src/sponge.rs', lines 73:4-83:5
    Visibility: public -/
@[rust_loop]
def sponge.sponge_loop1
  {T0 : Type} (coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst :
  core.ops.function.Fn T0 (Slice Bool) (alloc.vec.Vec Bool)) (f : T0)
  (r : nat.Nat) (d : nat.Nat) (s : alloc.vec.Vec Bool) (z : bits.BitStr) :
  RustM bits.BitStr
  := do
  loop
    (fun (s1, z1) => sponge.sponge_loop1.body
      coreopsfunctionFnT0TupleSharedSliceBoolVecBoolInst f r d s1 z1)
    (s, z)

/-- [pedantic_sha3::sponge::sponge]:
    Source: 'sha3/spec/src/sponge.rs', lines 32:0-84:1
    Visibility: public -/
def sponge.sponge
  {T0 : Type} {T1 : Type} (coreopsfunctionFnT0TupleShared0SliceBoolVecBoolInst
  : core.ops.function.Fn T0 (Slice Bool) (alloc.vec.Vec Bool))
  (coreopsfunctionFnT1PairNatNatBitStrInst : core.ops.function.Fn T1 (nat.Nat
  × nat.Nat) bits.BitStr) (f : T0) (b : Std.Usize) (pad : T1) (r : nat.Nat)
  (n : bits.BitStr) (d : nat.Nat) :
  RustM bits.BitStr
  := do
  let n1 ← nat.Nat.new 0#u128
  let b1 ← nat.Nat.Insts.CoreCmpPartialOrdNat.gt r n1
  massert b1
  let n2 ← nat.Nat.from_usize b
  let b2 ← nat.Nat.Insts.CoreCmpPartialOrdNat.lt r n2
  massert b2
  let n3 ← bits.BitStr.len n
  let bs ← coreopsfunctionFnT1PairNatNatBitStrInst.call pad (r, n3)
  let p ← bits.BitStr.concat n bs
  let n4 ← bits.BitStr.len p
  let n5 ← nat.Nat.Insts.CoreOpsArithRemNatNat.rem n4 r
  let b3 ← nat.Nat.Insts.CoreCmpPartialEqNat.eq n5 n1
  massert b3
  let blocks ← nat.Nat.Insts.CoreOpsArithDivNatNat.div n4 r
  let i ← nat.Nat.to_usize r
  let c ← b - i
  let s ← bits.zeros b
  let s1 ←
    sponge.sponge_loop0 coreopsfunctionFnT0TupleShared0SliceBoolVecBoolInst f r
      p blocks c s n1
  let z ← bits.BitStr.empty
  let z1 ←
    sponge.sponge_loop1 coreopsfunctionFnT0TupleShared0SliceBoolVecBoolInst f r
      d s1 z
  bits.BitStr.trunc z1 d

/-- [pedantic_sha3::sponge::keccak_c]:
    Source: 'sha3/spec/src/sponge.rs', lines 94:0-105:1
    Visibility: public -/
def sponge.keccak_c
  (c : Std.Usize) (n : bits.BitStr) (d : nat.Nat) : RustM bits.BitStr := do
  let i ← sponge.B - c
  let n1 ← nat.Nat.from_usize i
  sponge.sponge
    sponge.keccak_c.closure.Insts.CoreOpsFunctionFnTupleSharedSliceBoolVecBool
    sponge.keccak_c.closure_1.Insts.CoreOpsFunctionFnPairNatNatBitStr ()
    sponge.B () n1 n d

/-- [pedantic_sha3::sha3::HASH_SUFFIX]
    Source: 'sha3/spec/src/sha3.rs', lines 16:0-16:48
    Visibility: public -/
@[global_simps, irreducible]
def sha3.HASH_SUFFIX : Array Bool 2#usize := Array.make 2#usize [ false, true ]

/-- [pedantic_sha3::sha3::sha3_224]:
    Source: 'sha3/spec/src/sha3.rs', lines 22:0-28:1
    Visibility: public -/
def sha3.sha3_224 (m : bits.BitStr) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  let n ← nat.Nat.new 224#u128
  sponge.keccak_c 448#usize bs1 n

/-- [pedantic_sha3::bytes::sha3_224]:
    Source: 'sha3/spec/src/bytes.rs', lines 17:8-22:9
    Visibility: public -/
def bytes.sha3_224 (m : Slice Std.U8) : RustM (Array Std.U8 28#usize) := do
  let bs ← bits.h2b_full m
  let bs1 ← sha3.sha3_224 bs
  let digest ← bits.b2h bs1
  let out := Array.repeat 28#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  ok (to_slice_mut_back s2)

/-- [pedantic_sha3::sha3::sha3_256]:
    Source: 'sha3/spec/src/sha3.rs', lines 31:0-37:1
    Visibility: public -/
def sha3.sha3_256 (m : bits.BitStr) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  let n ← nat.Nat.new 256#u128
  sponge.keccak_c 512#usize bs1 n

/-- [pedantic_sha3::bytes::sha3_256]:
    Source: 'sha3/spec/src/bytes.rs', lines 17:8-22:9
    Visibility: public -/
def bytes.sha3_256 (m : Slice Std.U8) : RustM (Array Std.U8 32#usize) := do
  let bs ← bits.h2b_full m
  let bs1 ← sha3.sha3_256 bs
  let digest ← bits.b2h bs1
  let out := Array.repeat 32#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  ok (to_slice_mut_back s2)

/-- [pedantic_sha3::sha3::sha3_384]:
    Source: 'sha3/spec/src/sha3.rs', lines 40:0-46:1
    Visibility: public -/
def sha3.sha3_384 (m : bits.BitStr) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  let n ← nat.Nat.new 384#u128
  sponge.keccak_c 768#usize bs1 n

/-- [pedantic_sha3::bytes::sha3_384]:
    Source: 'sha3/spec/src/bytes.rs', lines 17:8-22:9
    Visibility: public -/
def bytes.sha3_384 (m : Slice Std.U8) : RustM (Array Std.U8 48#usize) := do
  let bs ← bits.h2b_full m
  let bs1 ← sha3.sha3_384 bs
  let digest ← bits.b2h bs1
  let out := Array.repeat 48#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  ok (to_slice_mut_back s2)

/-- [pedantic_sha3::sha3::sha3_512]:
    Source: 'sha3/spec/src/sha3.rs', lines 49:0-55:1
    Visibility: public -/
def sha3.sha3_512 (m : bits.BitStr) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  let n ← nat.Nat.new 512#u128
  sponge.keccak_c 1024#usize bs1 n

/-- [pedantic_sha3::bytes::sha3_512]:
    Source: 'sha3/spec/src/bytes.rs', lines 17:8-22:9
    Visibility: public -/
def bytes.sha3_512 (m : Slice Std.U8) : RustM (Array Std.U8 64#usize) := do
  let bs ← bits.h2b_full m
  let bs1 ← sha3.sha3_512 bs
  let digest ← bits.b2h bs1
  let out := Array.repeat 64#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  ok (to_slice_mut_back s2)

/-- [pedantic_sha3::sha3::XOF_SUFFIX]
    Source: 'sha3/spec/src/sha3.rs', lines 19:0-19:58
    Visibility: public -/
@[global_simps, irreducible]
def sha3.XOF_SUFFIX : Array Bool 4#usize := Array.repeat 4#usize true

/-- [pedantic_sha3::sha3::shake128]:
    Source: 'sha3/spec/src/sha3.rs', lines 58:0-60:1
    Visibility: public -/
def sha3.shake128 (m : bits.BitStr) (d : nat.Nat) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.XOF_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  sponge.keccak_c 256#usize bs1 d

/-- [pedantic_sha3::bytes::shake128]:
    Source: 'sha3/spec/src/bytes.rs', lines 40:0-45:1
    Visibility: public -/
def bytes.shake128
  (m : Slice Std.U8) (out_bytes : Std.Usize) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let bs ← bits.h2b_full m
  let n ← nat.Nat.from_usize out_bytes
  let n1 ← nat.Nat.new 8#u128
  let n2 ← nat.Nat.Insts.CoreOpsArithMulNatNat.mul n n1
  let bs1 ← sha3.shake128 bs n2
  bits.b2h bs1

/-- [pedantic_sha3::sha3::shake256]:
    Source: 'sha3/spec/src/sha3.rs', lines 63:0-65:1
    Visibility: public -/
def sha3.shake256 (m : bits.BitStr) (d : nat.Nat) : RustM bits.BitStr := do
  let s ← lift (Array.to_slice sha3.XOF_SUFFIX)
  let bs ← bits.BitStr.from_bits s
  let bs1 ← bits.BitStr.concat m bs
  sponge.keccak_c 512#usize bs1 d

/-- [pedantic_sha3::bytes::shake256]:
    Source: 'sha3/spec/src/bytes.rs', lines 48:0-53:1
    Visibility: public -/
def bytes.shake256
  (m : Slice Std.U8) (out_bytes : Std.Usize) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let bs ← bits.h2b_full m
  let n ← nat.Nat.from_usize out_bytes
  let n1 ← nat.Nat.new 8#u128
  let n2 ← nat.Nat.Insts.CoreOpsArithMulNatNat.mul n n1
  let bs1 ← sha3.shake256 bs n2
  bits.b2h bs1

/-- [pedantic_sha3::keccak_p::keccak_f]:
    Source: 'sha3/spec/src/keccak_p.rs', lines 45:0-47:1
    Visibility: public -/
def keccak_p.keccak_f
  (W : Std.Usize) (s : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let i ← state_array.StateArray.L W
  let i1 ← 2#usize * i
  let i2 ← 12#usize + i1
  keccak_p.keccak_p W s i2

/-- Trait implementation: [pedantic_sha3::nat::{impl core::clone::Clone for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 54:0-59:1 -/
@[reducible]
impl_def nat.Nat.Insts.CoreCloneClone : core.clone.Clone nat.Nat := {
  clone := nat.Nat.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    nat.Nat.Insts.CoreCloneClone
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::marker::Copy for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 61:0-61:20 -/
@[reducible]
def nat.Nat.Insts.CoreMarkerCopy : core.marker.Copy nat.Nat := {
  cloneCloneInst := nat.Nat.Insts.CoreCloneClone
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::ops::arith::Add<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 96:0-105:1 -/
@[reducible]
def nat.Nat.Insts.CoreOpsArithAddNatNat : core.ops.arith.Add nat.Nat nat.Nat
  nat.Nat := {
  add := nat.Nat.Insts.CoreOpsArithAddNatNat.add
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::ops::arith::Sub<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 107:0-119:1 -/
@[reducible]
def nat.Nat.Insts.CoreOpsArithSubNatNat : core.ops.arith.Sub nat.Nat nat.Nat
  nat.Nat := {
  sub := nat.Nat.Insts.CoreOpsArithSubNatNat.sub
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::ops::arith::Mul<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 121:0-130:1 -/
@[reducible]
def nat.Nat.Insts.CoreOpsArithMulNatNat : core.ops.arith.Mul nat.Nat nat.Nat
  nat.Nat := {
  mul := nat.Nat.Insts.CoreOpsArithMulNatNat.mul
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::ops::arith::Div<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 132:0-141:1 -/
@[reducible]
def nat.Nat.Insts.CoreOpsArithDivNatNat : core.ops.arith.Div nat.Nat nat.Nat
  nat.Nat := {
  div := nat.Nat.Insts.CoreOpsArithDivNatNat.div
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::ops::arith::Rem<pedantic_sha3::nat::Nat, pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 143:0-152:1 -/
@[reducible]
def nat.Nat.Insts.CoreOpsArithRemNatNat : core.ops.arith.Rem nat.Nat nat.Nat
  nat.Nat := {
  rem := nat.Nat.Insts.CoreOpsArithRemNatNat.rem
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::cmp::PartialEq<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 159:0-169:1 -/
@[reducible]
def nat.Nat.Insts.CoreCmpPartialEqNat : core.cmp.PartialEq nat.Nat nat.Nat := {
  eq := nat.Nat.Insts.CoreCmpPartialEqNat.eq
  ne := nat.Nat.Insts.CoreCmpPartialEqNat.ne
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::cmp::Eq for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 171:0-171:18 -/
@[reducible]
impl_def nat.Nat.Insts.CoreCmpEq : core.cmp.Eq nat.Nat := {
  PartialEqInst := nat.Nat.Insts.CoreCmpPartialEqNat
}

/-- Trait implementation: [pedantic_sha3::nat::{impl core::cmp::PartialOrd<pedantic_sha3::nat::Nat> for pedantic_sha3::nat::Nat}]
    Source: 'sha3/spec/src/nat.rs', lines 173:0-204:1 -/
@[reducible]
def nat.Nat.Insts.CoreCmpPartialOrdNat : core.cmp.PartialOrd nat.Nat nat.Nat
  := {
  PartialEqInst := nat.Nat.Insts.CoreCmpPartialEqNat
  partial_cmp := nat.Nat.Insts.CoreCmpPartialOrdNat.partial_cmp
  lt := nat.Nat.Insts.CoreCmpPartialOrdNat.lt
  le := nat.Nat.Insts.CoreCmpPartialOrdNat.le
  gt := nat.Nat.Insts.CoreCmpPartialOrdNat.gt
  ge := nat.Nat.Insts.CoreCmpPartialOrdNat.ge
}

/-- [pedantic_sha3::state_array::{impl core::clone::Clone for pedantic_sha3::state_array::StateArray<W>}::clone]:
    Source: 'sha3/spec/src/state_array.rs', lines 16:9-16:14
    Visibility: public -/
def state_array.StateArray.Insts.CoreCloneClone.clone
  {W : Std.Usize} (self : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  ok self

/-- Trait implementation: [pedantic_sha3::state_array::{impl core::clone::Clone for pedantic_sha3::state_array::StateArray<W>}]
    Source: 'sha3/spec/src/state_array.rs', lines 16:9-16:14 -/
@[reducible]
impl_def state_array.StateArray.Insts.CoreCloneClone (W : Std.Usize) :
  core.clone.Clone (state_array.StateArray W) := {
  clone := state_array.StateArray.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    (state_array.StateArray.Insts.CoreCloneClone W)
}

/-- Trait implementation: [pedantic_sha3::state_array::{impl core::marker::Copy for pedantic_sha3::state_array::StateArray<W>}]
    Source: 'sha3/spec/src/state_array.rs', lines 16:16-16:20 -/
@[reducible]
def state_array.StateArray.Insts.CoreMarkerCopy (W : Std.Usize) :
  core.marker.Copy (state_array.StateArray W) := {
  cloneCloneInst := state_array.StateArray.Insts.CoreCloneClone W
}

/-- Trait implementation: [pedantic_sha3::state_array::{impl core::marker::StructuralPartialEq for pedantic_sha3::state_array::StateArray<W>}]
    Source: 'sha3/spec/src/state_array.rs', lines 16:22-16:31 -/
@[reducible]
def state_array.StateArray.Insts.CoreMarkerStructuralPartialEq (W : Std.Usize)
  : core.marker.StructuralPartialEq (state_array.StateArray W) := {
}

/-- [pedantic_sha3::state_array::{impl core::cmp::PartialEq<pedantic_sha3::state_array::StateArray<W>> for pedantic_sha3::state_array::StateArray<W>}::eq]:
    Source: 'sha3/spec/src/state_array.rs', lines 16:22-16:31
    Visibility: public -/
def state_array.StateArray.Insts.CoreCmpPartialEqStateArray.eq
  {W : Std.Usize} (self : state_array.StateArray W)
  (other : state_array.StateArray W) :
  RustM Bool
  := do
  core.Array.Insts.CoreCmpPartialEqArray.eq
    (core.Array.Insts.CoreCmpPartialEqArray 5#usize
    (core.Array.Insts.CoreCmpPartialEqArray W
    core.Bool.Insts.CoreCmpPartialEqBool)) self.a other.a

/-- Trait implementation: [pedantic_sha3::state_array::{impl core::cmp::PartialEq<pedantic_sha3::state_array::StateArray<W>> for pedantic_sha3::state_array::StateArray<W>}]
    Source: 'sha3/spec/src/state_array.rs', lines 16:22-16:31 -/
@[reducible]
impl_def state_array.StateArray.Insts.CoreCmpPartialEqStateArray (W :
  Std.Usize) : core.cmp.PartialEq (state_array.StateArray W)
  (state_array.StateArray W) := {
  eq := state_array.StateArray.Insts.CoreCmpPartialEqStateArray.eq
  ne := core.cmp.PartialEq.ne.default
    (state_array.StateArray.Insts.CoreCmpPartialEqStateArray W)
}

/-- Trait implementation: [pedantic_sha3::state_array::{impl core::cmp::Eq for pedantic_sha3::state_array::StateArray<W>}]
    Source: 'sha3/spec/src/state_array.rs', lines 16:33-16:35 -/
@[reducible]
def state_array.StateArray.Insts.CoreCmpEq (W : Std.Usize) : core.cmp.Eq
  (state_array.StateArray W) := {
  PartialEqInst := state_array.StateArray.Insts.CoreCmpPartialEqStateArray W
}

/-- [pedantic_sha3::state_array::{pedantic_sha3::state_array::StateArray<W>}::W#1]
    Source: 'sha3/spec/src/state_array.rs', lines 24:4-24:27
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.W_1 (W : Std.Usize) : Std.Usize := W

end pedantic_sha3
