-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedantic_sha3]: type definitions
import Aeneas
import CoreModels
import PedanticSha3.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedantic_sha3

/-- [pedantic_sha3::sponge::keccak_c::closure#1]
    Source: 'sha3/spec/src/sponge.rs', lines 100:8-100:33 -/
@[reducible]
def sponge.keccak_c.closure_1 := Unit

/-- [pedantic_sha3::sponge::keccak_c::closure]
    Source: 'sha3/spec/src/sponge.rs', lines 98:8-98:41 -/
@[reducible]
def sponge.keccak_c.closure := Unit

/-- [pedantic_sha3::state_array::StateArray]
    Source: 'sha3/spec/src/state_array.rs', lines 17:0-20:1
    Visibility: public -/
structure state_array.StateArray (W : Std.Usize) where
  a : Array (Array (Array Bool W) 5#usize) 5#usize

end pedantic_sha3
