-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedantic_sha3]: external types.
-- This is a template file: hax seeded PedanticSha3/Assumptions/TypesExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [pedantic_sha3::bits::BitStr]
    Source: 'sha3/spec/src/bits.rs', lines 53:0-62:1
    Visibility: public -/
axiom bits.BitStr : Type

/-- [pedantic_sha3::nat::Nat]
    Source: 'sha3/spec/src/nat.rs', lines 48:0-48:32
    Visibility: public -/
axiom nat.Nat : Type

