-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: proof obligations
import Aeneas
import CoreModels
import LibcruxIotSha3.Extraction.Types
import LibcruxIotSha3.Extraction.Funs
import LibcruxIotSha3.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_sha3

@[spec]
theorem hash.spec.proof (LEN : Std.Usize) (algorithm : Algorithm)
  (payload : Slice Std.U8) : hash.spec LEN algorithm payload
  := by sorry

@[spec]
theorem sha224.spec.proof (payload : Slice Std.U8) : sha224.spec payload
  := by sorry

@[spec]
theorem sha224_ema.spec.proof (digest : Slice Std.U8) (payload : Slice Std.U8)
  : sha224_ema.spec digest payload
  := by sorry

@[spec]
theorem sha256.spec.proof (payload : Slice Std.U8) : sha256.spec payload
  := by sorry

@[spec]
theorem sha256_ema.spec.proof (digest : Slice Std.U8) (payload : Slice Std.U8)
  : sha256_ema.spec digest payload
  := by sorry

@[spec]
theorem sha384.spec.proof (payload : Slice Std.U8) : sha384.spec payload
  := by sorry

@[spec]
theorem sha384_ema.spec.proof (digest : Slice Std.U8) (payload : Slice Std.U8)
  : sha384_ema.spec digest payload
  := by sorry

@[spec]
theorem sha512.spec.proof (payload : Slice Std.U8) : sha512.spec payload
  := by sorry

@[spec]
theorem sha512_ema.spec.proof (digest : Slice Std.U8) (payload : Slice Std.U8)
  : sha512_ema.spec digest payload
  := by sorry

@[spec]
theorem shake128.spec.proof (BYTES : Std.Usize) (data : Slice Std.U8) :
  shake128.spec BYTES data
  := by sorry

@[spec]
theorem shake128_ema.spec.proof (out : Slice Std.U8) (data : Slice Std.U8) :
  shake128_ema.spec out data
  := by sorry

@[spec]
theorem shake256.spec.proof (BYTES : Std.Usize) (data : Slice Std.U8) :
  shake256.spec BYTES data
  := by sorry

@[spec]
theorem shake256_ema.spec.proof (out : Slice Std.U8) (data : Slice Std.U8) :
  shake256_ema.spec out data
  := by sorry

end libcrux_iot_sha3
