-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import LibcruxIotSha3.Extraction.Types
import LibcruxIotSha3.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_sha3


/-- [libcrux_iot_sha3::hash::pre]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 163:0-163:51 -/
@[reducible]
def hash.pre
  (LEN : Std.Usize) (algorithm : Algorithm) (payload : Slice Std.U8) :
  RustM Bool
  := do
  let i ← digest_size algorithm
  ok (LEN = i)

/-- [libcrux_iot_sha3::hash::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 164:0-164:101 -/
@[reducible]
def hash.post
  {LEN : Std.Usize} (algorithm : Algorithm) (payload : Slice Std.U8)
  (out : Array Std.U8 LEN) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s1 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  digest_matches algorithm s s1

def hash.spec (LEN : Std.Usize) (algorithm : Algorithm)
  (payload : Slice Std.U8) : Prop :=
  (hash.pre LEN algorithm payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  hash LEN algorithm payload
  ⦃ ⇓ res => ⌜ (hash.post algorithm payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha224::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 194:0-195:69 -/
@[reducible]
def sha224.post
  (payload : Slice Std.U8) (out : Array Std.U8 28#usize) : RustM Bool := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a1 ← pedantic_sha3.bytes.sha3_224 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a1 ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha224.spec (payload : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  sha224 payload
  ⦃ ⇓ res => ⌜ (sha224.post payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha224_ema::pre]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 213:0-213:58 -/
@[reducible]
def sha224_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len digest
  ok (i = SHA3_224_DIGEST_SIZE)

/-- [libcrux_iot_sha3::sha224_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 214:0-215:74 -/
@[reducible]
def sha224_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a ← pedantic_sha3.bytes.sha3_224 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha224_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha224_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha224_ema digest payload
  ⦃ ⇓ res => ⌜ (sha224_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha256::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 224:0-225:69 -/
@[reducible]
def sha256.post
  (payload : Slice Std.U8) (out : Array Std.U8 32#usize) : RustM Bool := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a1 ← pedantic_sha3.bytes.sha3_256 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a1 ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha256.spec (payload : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  sha256 payload
  ⦃ ⇓ res => ⌜ (sha256.post payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha256_ema::pre]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 243:0-243:58 -/
@[reducible]
def sha256_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len digest
  ok (i = SHA3_256_DIGEST_SIZE)

/-- [libcrux_iot_sha3::sha256_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 244:0-245:74 -/
@[reducible]
def sha256_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a ← pedantic_sha3.bytes.sha3_256 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha256_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha256_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha256_ema digest payload
  ⦃ ⇓ res => ⌜ (sha256_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha384::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 254:0-255:69 -/
@[reducible]
def sha384.post
  (payload : Slice Std.U8) (out : Array Std.U8 48#usize) : RustM Bool := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a1 ← pedantic_sha3.bytes.sha3_384 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a1 ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha384.spec (payload : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  sha384 payload
  ⦃ ⇓ res => ⌜ (sha384.post payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha384_ema::pre]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 273:0-273:58 -/
@[reducible]
def sha384_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len digest
  ok (i = SHA3_384_DIGEST_SIZE)

/-- [libcrux_iot_sha3::sha384_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 274:0-275:74 -/
@[reducible]
def sha384_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a ← pedantic_sha3.bytes.sha3_384 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha384_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha384_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha384_ema digest payload
  ⦃ ⇓ res => ⌜ (sha384_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha512::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 284:0-285:69 -/
@[reducible]
def sha512.post
  (payload : Slice Std.U8) (out : Array Std.U8 64#usize) : RustM Bool := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a1 ← pedantic_sha3.bytes.sha3_512 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a1 ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha512.spec (payload : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  sha512 payload
  ⦃ ⇓ res => ⌜ (sha512.post payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha512_ema::pre]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 303:0-303:58 -/
@[reducible]
def sha512_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len digest
  ok (i = SHA3_512_DIGEST_SIZE)

/-- [libcrux_iot_sha3::sha512_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 304:0-305:74 -/
@[reducible]
def sha512_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
  let a ← pedantic_sha3.bytes.sha3_512 s1
  let s2 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def sha512_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha512_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha512_ema digest payload
  ⦃ ⇓ res => ⌜ (sha512_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake128::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 314:0-315:73 -/
@[reducible]
def shake128.post
  {BYTES : Std.Usize} (data : Slice Std.U8) (out : Array Std.U8 BYTES) :
  RustM Bool
  := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let v ← pedantic_sha3.bytes.shake128 s1 BYTES
  let s2 ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) v ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def shake128.spec (BYTES : Std.Usize) (data : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  shake128 BYTES data
  ⦃ ⇓ res => ⌜ (shake128.post data res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake128_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 332:0-333:82 -/
@[reducible]
def shake128_ema.post
  (out : Slice Std.U8) (data : Slice Std.U8) (out_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let i ← core.slice.Slice.len out
  let v ← pedantic_sha3.bytes.shake128 s1 i
  let s2 ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) v ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def shake128_ema.spec (out : Slice Std.U8) (data : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  shake128_ema out data
  ⦃ ⇓ res => ⌜ (shake128_ema.post out data res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake256::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 339:0-340:73 -/
@[reducible]
def shake256.post
  {BYTES : Std.Usize} (data : Slice Std.U8) (out : Array Std.U8 BYTES) :
  RustM Bool
  := do
  let a ←
    libcrux_secrets.Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) a ()
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let v ← pedantic_sha3.bytes.shake256 s1 BYTES
  let s2 ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) v ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def shake256.spec (BYTES : Std.Usize) (data : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  shake256 BYTES data
  ⦃ ⇓ res => ⌜ (shake256.post data res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake256_ema::post]:
    Source: 'sha3/libcrux-iot-5df472a/annotated-upstream/src/lib.rs', lines 357:0-358:82 -/
@[reducible]
def shake256_ema.post
  (out : Slice Std.U8) (data : Slice Std.U8) (out_future : Slice Std.U8) :
  RustM Bool
  := do
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar out_future
  let s1 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let i ← core.slice.Slice.len out
  let v ← pedantic_sha3.bytes.shake256 s1 i
  let s2 ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) v ()
  core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8 s
    s2

def shake256_ema.spec (out : Slice Std.U8) (data : Slice Std.U8) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  shake256_ema out data
  ⦃ ⇓ res => ⌜ (shake256_ema.post out data res).holds ⌝ ⦄

end libcrux_iot_sha3
